name: build

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 13 * * *'
  workflow_dispatch: 

jobs:
  build:

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - run: brew install ninja pkg-config
      - run: make tools
      - run: make clean
      - run: make
      - name: Verify arm64 binary
        run: |
          uname -m
          file PathOfBuilding.app/Contents/MacOS/PathOfBuilding
      - run: zip -rq PathOfBuilding.zip PathOfBuilding.app

      - id: get-version
        run: |
          version=$(sed -n 's/^.*number="\([0-9.]*\)".*$/\1/p' PathOfBuilding/manifest.xml)
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"
      - name: Upload MacOS artifacts into Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "PathOfBuilding.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: v${{ steps.get-version.outputs.VERSION }}
        if: github.ref == 'refs/heads/master'